-- MySQL Script generated by MySQL Workbench
-- 09/13/18 03:59:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kgp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kgp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kgp` DEFAULT CHARACTER SET utf8 ;
USE `kgp` ;

-- -----------------------------------------------------
-- Table `kgp`.`billing_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`billing_type` (
  `idbilling_type` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `notation` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idbilling_type`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`clinical_institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`clinical_institution` (
  `id_clinical_institution` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `notation` VARCHAR(100) NOT NULL COMMENT '',
  `onset` DATE NOT NULL COMMENT '',
  `city` VARCHAR(45) NOT NULL COMMENT '',
  `postal_code` VARCHAR(5) NOT NULL COMMENT '',
  `street` VARCHAR(100) NOT NULL COMMENT '',
  `short_notation` VARCHAR(45) NOT NULL COMMENT '',
  `allocator` TINYBLOB NOT NULL COMMENT '',
  PRIMARY KEY (`id_clinical_institution`)  COMMENT '',
  UNIQUE INDEX `notation_UNIQUE` (`notation` ASC)  COMMENT '',
  UNIQUE INDEX `short_notation_UNIQUE` (`short_notation` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`staff` (
  `idstaff` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `firstname` VARCHAR(100) NOT NULL COMMENT '',
  `birth` DATE NULL DEFAULT NULL COMMENT '',
  `username` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `password` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `admin` TINYBLOB NULL DEFAULT NULL COMMENT '',
  `sex` INT(1) NOT NULL DEFAULT '0' COMMENT '',
  `onset` DATE NOT NULL COMMENT '',
  `expiry` DATE NULL DEFAULT NULL COMMENT '',
  `alias` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idstaff`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`clinical_institution_has_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`clinical_institution_has_staff` (
  `id_clinical_institution_has_staff` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_clinical_institution` INT(11) NOT NULL COMMENT '',
  `id_staff` INT(11) NOT NULL COMMENT '',
  `position` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_clinical_institution`, `id_staff`)  COMMENT '',
  UNIQUE INDEX `idclinical_instituion_has_staff_UNIQUE` (`id_clinical_institution_has_staff` ASC)  COMMENT '',
  INDEX `fk_staff_idx` (`id_staff` ASC)  COMMENT '',
  CONSTRAINT `fk_institution`
    FOREIGN KEY (`id_clinical_institution`)
    REFERENCES `kgp`.`clinical_institution` (`id_clinical_institution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff`
    FOREIGN KEY (`id_staff`)
    REFERENCES `kgp`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`data_path`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`data_path` (
  `iddata_path` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `path` VARCHAR(300) NOT NULL COMMENT 'the path (string) of the directory, where the examination files are stored',
  PRIMARY KEY (`iddata_path`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`manufacturer` (
  `idmanufacturer` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `notation` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idmanufacturer`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`electrode_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`electrode_type` (
  `idelectrode_type` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `length` INT(11) NOT NULL COMMENT '',
  `id_manufacturer` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idelectrode_type`)  COMMENT '',
  INDEX `fk_manufacturer_idx` (`id_manufacturer` ASC)  COMMENT '',
  CONSTRAINT `fk_manufacturer`
    FOREIGN KEY (`id_manufacturer`)
    REFERENCES `kgp`.`manufacturer` (`idmanufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`patient` (
  `idpatient` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_outpatient` BIGINT(10) NULL DEFAULT NULL COMMENT '',
  `id_inpatient` BIGINT(10) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT '',
  `firstname` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idpatient`)  COMMENT '',
  UNIQUE INDEX `id_ambulance_UNIQUE` (`id_outpatient` ASC)  COMMENT '',
  UNIQUE INDEX `id_stationary_UNIQUE` (`id_inpatient` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`physician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`physician` (
  `idphysician` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idstaff` INT(11) NOT NULL COMMENT '',
  `surname` VARCHAR(100) NOT NULL COMMENT '',
  `title` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `status` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `alias` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idphysician`)  COMMENT '',
  UNIQUE INDEX `alias_UNIQUE` (`alias` ASC)  COMMENT '',
  INDEX `fk_physician_idx` (`idstaff` ASC)  COMMENT '',
  CONSTRAINT `fk_physician_staff`
    FOREIGN KEY (`idstaff`)
    REFERENCES `kgp`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`examination_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`examination_type` (
  `idexamination_type` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `notation` VARCHAR(100) NOT NULL COMMENT '',
  `id_path` INT(11) NULL DEFAULT NULL COMMENT 'file path of the data of this examination type if exists',
  PRIMARY KEY (`idexamination_type`)  COMMENT '',
  INDEX `fk_examType_to_path_idx` (`id_path` ASC)  COMMENT '',
  CONSTRAINT `fk_examType_to_path`
    FOREIGN KEY (`id_path`)
    REFERENCES `kgp`.`data_path` (`iddata_path`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`examination` (
  `idexamination` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_examtype` INT(11) NOT NULL COMMENT '',
  `id_physician` INT(11) NOT NULL COMMENT '',
  `id_patient` INT(11) NOT NULL COMMENT '',
  `id_billing_type` INT(11) NOT NULL COMMENT '',
  `filename` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `startDateTime` DATETIME NULL DEFAULT NULL COMMENT '',
  `endDateTime` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idexamination`)  COMMENT '',
  INDEX `fk_examtype_idx` (`id_examtype` ASC)  COMMENT '',
  INDEX `fk_physician_idx` (`id_physician` ASC)  COMMENT '',
  INDEX `fk_physician_idx_1` (`id_physician` ASC)  COMMENT '',
  INDEX `fk_billingtype_idx` (`id_billing_type` ASC)  COMMENT '',
  INDEX `fk_exam_to_patient_idx` (`id_patient` ASC)  COMMENT '',
  CONSTRAINT `fk_billingtype`
    FOREIGN KEY (`id_billing_type`)
    REFERENCES `kgp`.`billing_type` (`idbilling_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_to_patient`
    FOREIGN KEY (`id_patient`)
    REFERENCES `kgp`.`patient` (`idpatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fl_exam_to_physician`
    FOREIGN KEY (`id_physician`)
    REFERENCES `kgp`.`physician` (`idphysician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fx_exam_to_examtype`
    FOREIGN KEY (`id_examtype`)
    REFERENCES `kgp`.`examination_type` (`idexamination_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`pm_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`pm_type` (
  `idpm_type` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `notation` VARCHAR(45) NOT NULL COMMENT '',
  `id_manufacturer` INT(11) NOT NULL COMMENT '',
  `chamber` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idpm_type`)  COMMENT '',
  INDEX `fk_manufacturer_idx_1` (`id_manufacturer` ASC)  COMMENT '',
  CONSTRAINT `fk_pm_manufacturer`
    FOREIGN KEY (`id_manufacturer`)
    REFERENCES `kgp`.`manufacturer` (`idmanufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`pm_implant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`pm_implant` (
  `id_pm_implant` INT(11) NOT NULL COMMENT '',
  `id_exam` INT(11) NOT NULL COMMENT '',
  `pm_type` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pm_implant`)  COMMENT '',
  UNIQUE INDEX `id_exam_UNIQUE` (`id_exam` ASC)  COMMENT '',
  INDEX `fk_pm_type_idx` (`pm_type` ASC)  COMMENT '',
  CONSTRAINT `fk_exam`
    FOREIGN KEY (`id_exam`)
    REFERENCES `kgp`.`examination` (`idexamination`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pm_type`
    FOREIGN KEY (`pm_type`)
    REFERENCES `kgp`.`pm_type` (`idpm_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`electrode_implant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`electrode_implant` (
  `idelectrode_implant` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pm_implant` INT(11) NOT NULL COMMENT '',
  `id_electrode_type` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pm_implant`, `id_electrode_type`)  COMMENT '',
  UNIQUE INDEX `idelectrode_implant_UNIQUE` (`idelectrode_implant` ASC)  COMMENT '',
  INDEX `fk_electrode_type_idx` (`id_electrode_type` ASC)  COMMENT '',
  CONSTRAINT `fk_electrode_type`
    FOREIGN KEY (`id_electrode_type`)
    REFERENCES `kgp`.`electrode_type` (`idelectrode_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pm_implant`
    FOREIGN KEY (`id_pm_implant`)
    REFERENCES `kgp`.`pm_implant` (`id_pm_implant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`exam_assist_nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`exam_assist_nurse` (
  `idexam_assist_nurse` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_exam` INT(11) NOT NULL COMMENT '',
  `id_nurse` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_exam`, `id_nurse`)  COMMENT '',
  UNIQUE INDEX `idexam_assist_nurse_UNIQUE` (`idexam_assist_nurse` ASC)  COMMENT '',
  INDEX `fk_assist_nurse_to_nurse_idx` (`id_nurse` ASC)  COMMENT '',
  CONSTRAINT `fk_assist_nurse_to_exam`
    FOREIGN KEY (`id_exam`)
    REFERENCES `kgp`.`examination` (`idexamination`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assist_nurse_to_nurse`
    FOREIGN KEY (`id_nurse`)
    REFERENCES `kgp`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`exam_assist_physician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`exam_assist_physician` (
  `idexam_assist` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_exam` INT(11) NOT NULL COMMENT '',
  `id_physician` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_exam`, `id_physician`)  COMMENT '',
  UNIQUE INDEX `idexam_assist_UNIQUE` (`idexam_assist` ASC)  COMMENT '',
  INDEX `fk_assist_physician_to_physician_idx` (`id_physician` ASC)  COMMENT '',
  CONSTRAINT `fk_assist_physician_to_exam`
    FOREIGN KEY (`id_exam`)
    REFERENCES `kgp`.`examination` (`idexamination`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assist_physician_to_physician`
    FOREIGN KEY (`id_physician`)
    REFERENCES `kgp`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`lhk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`lhk` (
  `id_lhk` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_exam` INT(11) NOT NULL COMMENT '',
  `access_site` VARCHAR(45) NOT NULL COMMENT 'may be left or right',
  `access_artery` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id_lhk`)  COMMENT '',
  UNIQUE INDEX `id_exam_UNIQUE` (`id_exam` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Heart Catheter';


-- -----------------------------------------------------
-- Table `kgp`.`nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`nurse` (
  `idnurse` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_staff` INT(11) NOT NULL COMMENT '',
  `surname` VARCHAR(100) NOT NULL COMMENT '',
  `status` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `alias` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idnurse`)  COMMENT '',
  UNIQUE INDEX `alias_UNIQUE` (`alias` ASC)  COMMENT '',
  INDEX `fk_nurse_props_idx` (`id_staff` ASC)  COMMENT '',
  CONSTRAINT `fk_nurse_staff`
    FOREIGN KEY (`id_staff`)
    REFERENCES `kgp`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`patient_extended`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`patient_extended` (
  `idpatient_extended` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_patient` INT(11) NOT NULL COMMENT '',
  `surname` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idpatient_extended`)  COMMENT '',
  INDEX `fk_patient_idx` (`id_patient` ASC)  COMMENT '',
  CONSTRAINT `fk_patient`
    FOREIGN KEY (`id_patient`)
    REFERENCES `kgp`.`patient` (`idpatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`pci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`pci` (
  `id_pci` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_lhk` INT(11) NOT NULL COMMENT '',
  `id_vessel` INT(11) NOT NULL COMMENT '',
  `id_segment` INT(11) NOT NULL COMMENT '',
  `id_catheter` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pci`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'percutanous coronary intervention';


-- -----------------------------------------------------
-- Table `kgp`.`qualified_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`qualified_staff` (
  `idqualified_staff` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_staff` INT(11) NOT NULL COMMENT '',
  `id_examtype` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_staff`, `id_examtype`)  COMMENT '',
  UNIQUE INDEX `idqualified_physician_UNIQUE` (`idqualified_staff` ASC)  COMMENT '',
  INDEX `fk_examtype_examtype_idx` (`id_examtype` ASC)  COMMENT '',
  CONSTRAINT `fk_qs_examType`
    FOREIGN KEY (`id_examtype`)
    REFERENCES `kgp`.`examination_type` (`idexamination_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualifiedstaff_staff`
    FOREIGN KEY (`id_staff`)
    REFERENCES `kgp`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kgp`.`qualified_staff_has_examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kgp`.`qualified_staff_has_examination` (
  `idqualified_staff_has_examination` INT(11) NOT NULL COMMENT '',
  `id_qualified_staff` INT(11) NULL DEFAULT NULL COMMENT '',
  `id_examination` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idqualified_staff_has_examination`)  COMMENT '',
  INDEX `fk_qualifiedphysician_idx` (`id_qualified_staff` ASC)  COMMENT '',
  CONSTRAINT `fk_qualifiedstaff`
    FOREIGN KEY (`id_qualified_staff`)
    REFERENCES `kgp`.`qualified_staff` (`idqualified_staff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
